ci_methods: ["param_t", "param_z", "basic", "percentile", "bca", "agresti_coull", "wilson", "wald", "cloper_pearson", "exact"]

# Possible values for metrics (for reference, you will use one at a time)
metric:
  - "dsc"
  - "nsd"

# Possible values for summary_stat (choose one from here)
summary_stat:
  - "mean"
  - "median"
  - "trimmed_mean"
  - "std"
  - "iqr_length"

kernel:
  - "gaussian"
  - "tophat"
  - "epanechnikov"
  - "exponential"
  - "cosine"
  - "linear"

adaptive_bandwidth: true

# Trimmed mean thresholds (adjustable)
trimmed_mean_threshold: 0.25

sample_sizes: [10, 25, 50, 75, 100, 125, 150, 200, 250]

# Path to the data file, relative to the repository root
relative_data_path : "../data_matrix_grandchallenge_all.csv"

# Path to the output directory for saving results, relative to the repository root
relative_output_dir: "../results"  

# Number of samples to draw from KDE
n_samples: 10000