# ci_methods: ["basic", "percentile", "bca", "agresti_coull", "wilson", "exact", "wald", "logit_transform", "delong"]
ci_methods: ["logit_transform", "delong"]

# Possible values for metrics (for reference, you will use one at a time)
metric:
  - "accuracy"
  - "f1_score"
  - "balanced_accuracy"
  - "mcc"
  - "auc"
  - "ap"

average: "micro"
# Possible values for summary_stat (choose one from here)

kernel:
  - "gaussian"
  - "tophat"
  - "epanechnikov"
  - "exponential"
  - "cosine"
  - "linear"

adaptive_bandwidth: true

# Trimmed mean thresholds (adjustable)

sample_sizes: [10, 25, 50, 75, 100, 125, 150, 200, 250]

# Path to the data file, relative to the repository root
relative_data_path : "../data_matrix_classification.csv"

# Path to the output directory for saving results, relative to the repository root
relative_output_dir: "../results_classif_auc"

# Number of samples to draw from KDE
n_samples: 10000